# Generated by Django 4.1.6 on 2023-05-24 19:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trainingImages',
            field=models.ImageField(default='.jpg', upload_to=users.models.profile_image_upload_to),
        ),
    ]
