# Generated by Django 4.1.6 on 2023-05-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_trainingimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trainingImages',
        ),
    ]
