# Generated by Django 4.1.6 on 2023-05-25 23:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='.jpg', null=True, upload_to=users.models.profile_image_upload_to),
        ),
    ]
