# Generated by Django 4.2.1 on 2023-05-14 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_course_capturingtime_course_seessiontime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('user', models.ManyToManyField(related_name='lecture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
