# Generated by Django 4.2.1 on 2023-05-17 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_lecture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='lecture', to=settings.AUTH_USER_MODEL),
        ),
    ]
