# Generated by Django 4.1.6 on 2023-06-01 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lecture_type_alter_lecture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
