# Generated by Django 4.1.6 on 2023-06-01 15:16

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lecture_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=course.models.generate_code, max_length=5),
        ),
    ]
