# Generated by Django 4.1.6 on 2023-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sessionDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=10),
        ),
    ]
